name: Conic Launcher Auto Build
on:
  pull_request:
    paths:
      - ".github/workflows/build.yml"
  push:
    branches:
      - master

jobs:
  get-version:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Get app version
        id: current_version
        run: |
          echo "text=$(jq -r .version core/tauri.conf.json)" >> "$GITHUB_OUTPUT"

      - name: Get previous version
        id: previous_version
        run: |
          echo "text=$(git show HEAD~1:core/tauri.conf.json | jq -r .version)" >> $GITHUB_OUTPUT
    outputs:
      app_version: ${{ steps.current_version.outputs.text }}
      previous_app_version: ${{ steps.previous_version.outputs.text }}
  release:
    needs: [get-version]
    permissions:
      contents: write
    runs-on: ubuntu-22.04
    # if: needs.get-version.outputs.app_version != needs.get-version.outputs.previous_app_version
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: show version
        run: |
          echo ${{ needs.get-version.outputs.app_version }}
          echo ${{ needs.get-version.outputs.previous_app_version }}

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./release_files
      - name: Detect prerelease
        id: detect
        run: |
          if [[ "${{ needs.get-version.outputs.app_version }}" == *"alpha"* || "${{ needs.get-version.outputs.app_version }}" == *"beta"* || "${{ needs.get-version.outputs.app_version }}" == *"rc"* ]]; then
            echo "is_prerelease=true" >> $GITHUB_OUTPUT
          else
            echo "is_prerelease=false" >> $GITHUB_OUTPUT
          fi

      - name: Draft release
        id: drafter
        uses: release-drafter/release-drafter@v6
        with:
          version: ${{ needs.get-version.outputs.app_version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: show body
        env:
          BODY: ${{ steps.drafter.outputs.body }}

      - name: generate file (remove)
        run: |
          mkdir ./release_files
          echo 114514 > ./release_files/1.txt
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ needs.get-version.outputs.app_version }}
          name: Conic Launcher v${{ needs.get-version.outputs.app_version }}
          prerelease: ${{ steps.current_version.outputs.text }}
          body: ${{ steps.drafter.outputs.body }}
          files: ./release_files/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
